// Generated by Selenium IDE
// New Relic Synthetics Formatter for Selenium IDE
// Feel free to explore, or check out the full documentation
// https://docs.newrelic.com/docs/synthetics/new-relic-synthetics/scripting-monitors/writing-scripted-browsers
// for details

const assert = require("assert");
const urlRequest = require("urllib").request;
// Theshold for duration of entire script - fails test if script lasts longer than X (in ms)
// Script-wide timeout for all wait and waitAndFind functions (in ms)
var DefaultTimeout = 99999999;
var ScriptTimeout = 9999999;
var WaitTimeout = 99999999;
// Change to any User Agent you want to use.
// Leave as "default" or empty to use the Synthetics default.
var UserAgent = "default";
const By = $driver.By;
const browser = $browser.manage();
var vars = new Map();
const logger = (function ({
  timeout: e = 18e4,
  stepLogging: t = !1,
  insightsKey: n = "",
}) {
  const r = Date.now();
  var s = 0,
    o = "",
    i = 0,
    a = 0;
  function l({
    step: e = 0,
    msg: t = "",
    duration: r = 0,
    eventType: s = "SyntheticsCustom",
    custom: o = {},
  }) {
    if (void 0 === n || "" == n) return;
    var i = {
      method: "POST",
      headers: { "X-Insert-Key": n, "Content-Type": "application/json" },
      data: {
        eventType: s,
        step: e,
        message: t,
        duration: r,
        JOB_ID: $env.JOB_ID,
        MONITOR_ID: $env.MONITOR_ID,
        ACCOUNT_ID: $env.ACCOUNT_ID,
        LOCATION: $env.LOCATION,
        PROXY_HOST: $env.PROXY_HOST,
        PROXY_PORT: $env.PROXY_PORT,
      },
      dataType: "text",
    };
    const a = `https://insights-collector.newrelic.com/v1/accounts/${$env.ACCOUNT_ID}/events`;
    (i.data = Object.assign({}, i.data, o)), urlRequest(a, i);
  }
  function c(e, t, n = "") {
    e > a && 0 != a && _({ testCase: n });
    let i = `Step ${e}: ${t} STARTED at ${(s =
      Date.now() - r)}ms. testCase=${n}`;
    console.log(i), (o = t), (a = e);
  }
  function _({ testCase: i = "" }) {
    var c = Date.now() - r,
      _ = c - s;
    if (
      (console.log(
        `Step ${a}: ${o} FINISHED. It took ${_}ms to complete. testCase=${i}`
      ),
      t && n.length > 0
        ? l({ step: a, msg: o, duration: _, custom: { testCase: i } })
        : t && $util.insights.set(`Step ${a}: ${o}`, _),
      e > 0 && c > e)
    )
      throw new Error(
        "Script timed out. " +
          c +
          "ms is longer than script timeout threshold of " +
          e +
          "ms."
      );
  }
  return {
    logStep: function (e) {
      c(i++, e);
    },
    log: c,
    getStep: function () {
      return i;
    },
    end: _,
    endTestCase: function (e = "") {
      var i = Date.now() - r - s;
      console.log(`Step ${a}: ${o} FINISHED. It took ${i}ms to complete.`),
        t && n.length > 0
          ? l({ step: a, msg: o, duration: i, custom: { testCase: e } })
          : t && $util.insights.set(`Step ${a}: ${o}`, i),
        $util.insights.set("testCase", e),
        $util.insights.set("testCaseStatus", "Pass"),
        t &&
          n.length > 0 &&
          l({
            eventType: "SyntheticsTests",
            custom: { testCase: e, testCaseStatus: "Pass" },
          });
    },
    error: function (e, r = "") {
      console.log(`Error in Step ${a}: ${o}`),
        $util.insights.set("errorStep", "" + a),
        $util.insights.set("errorMsg", e.message),
        $util.insights.set("errorLineNumber", e.lineNumber),
        $util.insights.set("testCase", r),
        $util.insights.set("testCaseStatus", "fail"),
        t &&
          n.length > 0 &&
          l({
            eventType: "SyntheticsTests",
            custom: { testCase: r, testCaseStatus: "Fail" },
          });
    },
    postInsights: l,
  };
})({});
$browser
  .getCapabilities()
  .then(function () {
    $browser.manage().timeouts().setScriptTimeout(ScriptTimeout);
    $browser.manage().timeouts().pageLoadTimeout(DefaultTimeout);
    $browser.manage().timeouts().implicitlyWait(WaitTimeout);
  })
  .then(function () {
    return Promise.resolve(true)
    .then(function () {
        return (
          logger.log(
            1,
            "Open URL https://dummyURL/login",
            "PRP_STG_CREATEOpty_CREATEQuote_Pricing"
          ),
          $browser.get("https://dummyURL/login").then((e) => e)
        );
      })
      .then(function () {
        return (
          logger.log(
            2,
            "Set Window Size Width=1162 Height=742",
            "PRP_STG_CREATEOpty_CREATEQuote_Pricing"
          ),
          $browser
            .manage()
            .window()
            .setSize(1162, 742)
            .then((e) => e)
        );
      })
      .then(function () {
        return (
          logger.log(
            3,
            'Click By.id("USER")',
            "PRP_STG_CREATEOpty_CREATEQuote_Pricing"
          ),
          $browser
            .waitForAndFindElement(By.id("USER"), DefaultTimeout)
            .then((e) => (e.click(), Promise.resolve(!0)))
        );
      })
      .then(function () {
        return (
          logger.log(
            4,
            'Type "dummyUsername@yopmail.com" using locator By.id("USER")',
            "PRP_STG_CREATEOpty_CREATEQuote_Pricing"
          ),
          $browser
            .waitForAndFindElement(By.id("USER"), DefaultTimeout)
            .then(
              (e) => (
                e.sendKeys("dummyUsername@yopmail.com"), Promise.resolve(!0)
              )
            )
        );
      })
      .then(function () {
        return (
          logger.log(
            5,
            'Click By.id("PASSWORD")',
            "PRP_STG_CREATEOpty_CREATEQuote_Pricing"
          ),
          $browser
            .waitForAndFindElement(By.id("PASSWORD"), DefaultTimeout)
            .then((e) => (e.click(), Promise.resolve(!0)))
        );
      })
      .then(function () {
        return (
          logger.log(
            6,
            'Type "Number@1234" using locator By.id("PASSWORD")',
            "PRP_STG_CREATEOpty_CREATEQuote_Pricing"
          ),
          $browser
            .waitForAndFindElement(By.id("PASSWORD"), DefaultTimeout)
            .then((e) => (e.sendKeys("Number@1234"), Promise.resolve(!0)))
        );
      })
      .then(function () {
        return (
          logger.log(
            7,
            'Click By.id("_com_liferay_login_web_portlet_LoginPortlet_sign-in-btn")',
            "PRP_STG_CREATEOpty_CREATEQuote_Pricing"
          ),
          $browser
            .waitForAndFindElement(
              By.id("_com_liferay_login_web_portlet_LoginPortlet_sign-in-btn"),
              DefaultTimeout
            )
            .then((e) => (e.click(), Promise.resolve(!0)))
        );
      })
    .then(() => {
        $browser.sleep(30000)
        $browser.takeScreenshot()
    })
      .then(function () {
        return (
          logger.log(
            8,
            'Click By.id("add-quick-links")',
            "PRP_STG_CREATEOpty_CREATEQuote_Pricing"
          ),
          $browser
            .waitForAndFindElement(By.id('add-quick-links'), DefaultTimeout)
            .then((e) => (e.click(), Promise.resolve(!0)))
        );
      })
      .then(() => {
        $browser.sleep(30000)
        $browser.takeScreenshot()
    })
      .then(function () {
        return (
          logger.log(
            9,
            'Type "Integrated Quoting 2.0" using locator By.id("searchTools")',
            "PRP_STG_CREATEOpty_CREATEQuote_Pricing"
          ),
          $browser
            .waitForAndFindElement(By.id("searchTools"), DefaultTimeout)
            .then(
              (e) => (e.sendKeys("Integrated Quoting 2.0"), Promise.resolve(!0))
            )
        );
      })
      .then(function () {
        return (
          logger.log(10, "Send Key", "PRP_STG_CREATEOpty_CREATEQuote_Pricing"),
          $browser
            .waitForAndFindElement(By.id("searchTools"), DefaultTimeout)
            .then((e) => (e.sendKeys($driver.Key.ENTER), Promise.resolve(!0)))
        );
      })
      .then(function () {
        return (
          logger.log(
            11,
            'Click By.xpath("/html/body/div/div/section[2]/div/div/div/div/div[1]/section/div/div/div/div/div/div/div[2]/div/div[2]/div/div/ul/li[1]/div/div[1]/div[2]/span[2]/a/button")',
            "PRP_STG_CREATEOpty_CREATEQuote_Pricing"
          ),
          $browser
            .waitForAndFindElement(
              By.xpath(
                "/html/body/div/div/section[2]/div/div/div/div/div[1]/section/div/div/div/div/div/div/div[2]/div/div[2]/div/div/ul/li[1]/div/div[1]/div[2]/span[2]/a/button"
              ),
              DefaultTimeout
            )
            .then((e) => (e.click(), Promise.resolve(!0)))
        );
      })
  });


    $browser.getAllWindowHandles().then(function(windowHandlers) {
        $browser.switchTo().window(windowHandlers[1]).then(function() {
            $browser.getCapabilities().then(function () {
                $browser.manage().timeouts().setScriptTimeout(ScriptTimeout);
                $browser.manage().timeouts().pageLoadTimeout(DefaultTimeout);
                $browser.manage().timeouts().implicitlyWait(WaitTimeout);})
              .then( () => {
                return Promise.resolve(true)
                .then(function () {
                    return (
                      logger.log(
                        13,
                        'Click By.xpath("/html/body/div/div[3]/table/tbody/tr/td[2]/form/div[1]/div/div[2]/div/div/div/div/div[1]/span[2]/span/table/thead/tr[2]/td[2]/input")',
                        "PRP_STG_CREATEOpty_CREATEQuote_Pricing"
                      ),
                      $browser
                        .waitForAndFindElement(
                          By.xpath(
                            "/html/body/div/div[3]/table/tbody/tr/td[2]/form/div[1]/div/div[2]/div/div/div/div/div[1]/span[2]/span/table/thead/tr[2]/td[2]/input"
                          ),
                          DefaultTimeout
                        )
                        .then((e) => (e.click(), Promise.resolve(!0)))
                    );
                  })
                  .then(function () {
                    return (
                      logger.log(
                        14,
                        'Type "OPE-0008443524" using locator By.xpath("/html/body/div/div[3]/table/tbody/tr/td[2]/form/div[1]/div/div[2]/div/div/div/div/div[1]/span[2]/span/table/thead/tr[2]/td[2]/input")',
                        "PRP_STG_CREATEOpty_CREATEQuote_Pricing"
                      ),
                      $browser
                        .waitForAndFindElement(
                          By.xpath(
                            "/html/body/div/div[3]/table/tbody/tr/td[2]/form/div[1]/div/div[2]/div/div/div/div/div[1]/span[2]/span/table/thead/tr[2]/td[2]/input"
                          ),
                          DefaultTimeout
                        )
                        .then((e) => (e.sendKeys("OPE-0008443524"), Promise.resolve(!0)))
                    );
                  })
                  .then(function () {
                    return (
                      logger.log(15, "Send Key", "PRP_STG_CREATEOpty_CREATEQuote_Pricing"),
                      $browser
                        .waitForAndFindElement(
                          By.xpath(
                            "/html/body/div/div[3]/table/tbody/tr/td[2]/form/div[1]/div/div[2]/div/div/div/div/div[1]/span[2]/span/table/thead/tr[2]/td[2]/input"
                          ),
                          DefaultTimeout
                        )
                        .then((e) => (e.sendKeys($driver.Key.ENTER), Promise.resolve(!0)))
                    );
                  })
                  .then(() => { $browser.takeScreenshot() })
                  .then(function () {
                    return (
                      logger.log(
                        16,
                        'Click By.xpath("/html/body/div/div[3]/table/tbody/tr/td[2]/form/div[1]/div/div[2]/div/div/div/div/div[1]/span[2]/span/table/tbody/tr[5]/td[3]/span/a")',
                        "PRP_STG_CREATEOpty_CREATEQuote_Pricing"
                      ),
                      $browser
                        .waitForAndFindElement(
                          By.linkText(
                            "ShayanTest"
                          ),
                          DefaultTimeout
                        )
                        .then((e) => (e.click(), Promise.resolve(!0)))
                    );
                  })
                  .then(function () {
                    return (
                      logger.log(
                        17,
                        'Click By.xpath("/html/body/div/div[3]/table/tbody/tr/td[2]/div[2]/span[2]/span/div/div[5]/div/div/div[2]/div[2]/form/div[1]/span[1]/div/div[1]/div/div/div[1]/span/div[4]/div/div/div[3]/input")',
                        "PRP_STG_CREATEOpty_CREATEQuote_Pricing"
                      ),
                      $browser
                        .waitForAndFindElement(
                          By.xpath(
                            "/html/body/div/div[3]/table/tbody/tr/td[2]/div[2]/span[2]/span/div/div[5]/div/div/div[2]/div[2]/form/div[1]/span[1]/div/div[1]/div/div/div[1]/span/div[4]/div/div/div[3]/input"
                          ),
                          DefaultTimeout
                        )
                        .then((e) => (e.click(), Promise.resolve(!0)))
                    );
                  })
                  .then(function () {
                    return (
                      logger.log(
                        18,
                        'Click By.xpath("/html/body/div/div[3]/table/tbody/tr/td[2]/div[2]/span[2]/span/div/div[5]/div/div[1]/div[2]/div[2]/form[1]/div[1]/div/div[5]/div[3]/span/div[4]/div[2]/span/div/div/div[2]/table/tbody/tr/td[2]/input[2]")',
                        "PRP_STG_CREATEOpty_CREATEQuote_Pricing"
                      ),
                      $browser
                        .waitForAndFindElement(
                          By.xpath(
                            "/html/body/div/div[3]/table/tbody/tr/td[2]/div[2]/span[2]/span/div/div[5]/div/div[1]/div[2]/div[2]/form[1]/div[1]/div/div[5]/div[3]/span/div[4]/div[2]/span/div/div/div[2]/table/tbody/tr/td[2]/input[2]"
                          ),
                          DefaultTimeout
                        )
                        .then((e) => (e.click(), Promise.resolve(!0)))
                    );
                  })
                  .then(function () {
                    return (
                      logger.log(
                        19,
                        'Click By.id("QuotesTab")',
                        "PRP_STG_CREATEOpty_CREATEQuote_Pricing"
                      ),
                      $browser
                        .waitForAndFindElement(By.id("QuotesTab"), DefaultTimeout)
                        .then((e) => (e.click(), Promise.resolve(!0)))
                    );
                  })
                  .then(() => { $browser.sleep(500000) })
                  .then(() => { $browser.takeScreenshot() })
                  .then(function () {
                    return (
                      logger.log(
                        20,
                        'Click By.xpath("/html/body/div/div[3]/table/tbody/tr/td[2]/div[2]/span[2]/span/div/div[5]/div/div[1]/div[2]/div[2]/form[2]/div[1]/span/span/div/span/div/div/div/div[1]/div/div[4]/div/a[1]")',
                        "PRP_STG_CREATEOpty_CREATEQuote_Pricing"
                      ),
                      $browser
                        .waitForAndFindElement(
                          By.xpath(
                            "/html/body/div/div[3]/table/tbody/tr/td[2]/div[2]/span[2]/span/div/div[5]/div/div[1]/div[2]/div[2]/form[2]/div[1]/span/span/div/span/div/div/div/div[1]/div/div[4]/div/a[1]"
                          ),
                          DefaultTimeout
                        )
                        .then((e) => (e.click(), Promise.resolve(!0)))
                    );
                  })
                  .then(() => { $browser.sleep(500000) })
                  .then(() => { $browser.takeScreenshot() })
                  .then(function () {
                    return (
                      logger.log(
                        21,
                        "Mouse move",
                        "PRP_STG_CREATEOpty_CREATEQuote_Pricing"
                      ),
                      $browser
                        .waitForAndFindElement(
                          By.xpath(
                            "/html/body/div[9]/div/quotation-detail-page/div/form/div[2]/div[2]/div/tabs/div/div/div/pane/div/div/line-items/div/div/div[2]/div[4]/button"
                          ),
                          DefaultTimeout
                        )
                        .then((e) =>
                          Promise.resolve($browser.actions().mouseMove(e).perform())
                        )
                    );
                  })
                  .then(() => { $browser.sleep(120000) })
                  .then(function () {
                    return (
                      logger.log(
                        22,
                        'Click By.linkText("Add Product")',
                        "PRP_STG_CREATEOpty_CREATEQuote_Pricing"
                      ),
                      $browser
                        .waitForAndFindElement(By.linkText("Add Product"), DefaultTimeout)
                        .then((e) => (e.click(), Promise.resolve(!0)))
                    );
                  })
                  .then(function () {
                    return (
                      logger.log(
                        23,
                        'Click By.xpath("/html/body/div[9]/div/quotation-detail-page/div/form/div[2]/div[2]/div/tabs/div/div/div/pane/div/div/line-items/div/div/div[5]/div[2]/div/div[3]/div[2]/div/div/div/div[3]/div[1]/input")',
                        "PRP_STG_CREATEOpty_CREATEQuote_Pricing"
                      ),
                      $browser
                        .waitForAndFindElement(
                          By.xpath(
                            "/html/body/div[9]/div/quotation-detail-page/div/form/div[2]/div[2]/div/tabs/div/div/div/pane/div/div/line-items/div/div/div[5]/div[2]/div/div[3]/div[2]/div/div/div/div[3]/div[1]/input"
                          ),
                          DefaultTimeout
                        )
                        .then((e) => (e.click(), Promise.resolve(!0)))
                    );
                  })
                  .then(function () {
                    return (
                      logger.log(
                        24,
                        'Type "1" using locator By.xpath("/html/body/div[9]/div/quotation-detail-page/div/form/div[2]/div[2]/div/tabs/div/div/div/pane/div/div/line-items/div/div/div[5]/div[2]/div/div[3]/div[2]/div/div/div/div[3]/div[1]/input")',
                        "PRP_STG_CREATEOpty_CREATEQuote_Pricing"
                      ),
                      $browser
                        .waitForAndFindElement(
                          By.xpath(
                            "/html/body/div[9]/div/quotation-detail-page/div/form/div[2]/div[2]/div/tabs/div/div/div/pane/div/div/line-items/div/div/div[5]/div[2]/div/div[3]/div[2]/div/div/div/div[3]/div[1]/input"
                          ),
                          DefaultTimeout
                        )
                        .then((e) => (e.sendKeys("1"), Promise.resolve(!0)))
                    );
                  })
                  .then(function () {
                    return (
                      logger.log(
                        25,
                        'Click By.css(".ng-scope:nth-child(1) > .ng-scope > .ng-pristine")',
                        "PRP_STG_CREATEOpty_CREATEQuote_Pricing"
                      ),
                      $browser
                        .waitForAndFindElement(
                          By.css(".ng-scope:nth-child(1) > .ng-scope > .ng-pristine"),
                          DefaultTimeout
                        )
                        .then((e) => (e.click(), Promise.resolve(!0)))
                    );
                  })
                  .then(function () {
                    return (
                      logger.log(
                        26,
                        'Type "JW085A" using locator By.xpath("/html/body/div[9]/div/quotation-detail-page/div/form/div[2]/div[2]/div/tabs/div/div/div/pane/div/div/line-items/div/div/div[5]/div[2]/div/div[3]/div[2]/div/div/div/div[4]/div/div/input")',
                        "PRP_STG_CREATEOpty_CREATEQuote_Pricing"
                      ),
                      $browser
                        .waitForAndFindElement(
                          By.xpath(
                            "/html/body/div[9]/div/quotation-detail-page/div/form/div[2]/div[2]/div/tabs/div/div/div/pane/div/div/line-items/div/div/div[5]/div[2]/div/div[3]/div[2]/div/div/div/div[4]/div/div/input"
                          ),
                          DefaultTimeout
                        )
                        .then((e) => (e.sendKeys("JW085A"), Promise.resolve(!0)))
                    );
                  })
                  .then(function () {
                    return (
                      logger.log(27, "Send Key", "PRP_STG_CREATEOpty_CREATEQuote_Pricing"),
                      $browser
                        .waitForAndFindElement(
                          By.xpath(
                            "/html/body/div[9]/div/quotation-detail-page/div/form/div[2]/div[2]/div/tabs/div/div/div/pane/div/div/line-items/div/div/div[5]/div[2]/div/div[3]/div[2]/div/div/div/div[4]/div/div/input"
                          ),
                          DefaultTimeout
                        )
                        .then((e) => (e.sendKeys($driver.Key.ENTER), Promise.resolve(!0)))
                    );
                  })
                  .then(function () {
                    return (
                      logger.log(
                        28,
                        'Click By.css("#saveBtn > .btnText")',
                        "PRP_STG_CREATEOpty_CREATEQuote_Pricing"
                      ),
                      $browser
                        .waitForAndFindElement(
                          By.css("#saveBtn > .btnText"),
                          DefaultTimeout
                        )
                        .then((e) => (e.click(), Promise.resolve(!0)))
                    );
                  })
                  .then(function () {
                    return (
                      logger.log(
                        29,
                        'Click By.css("#refreshbtn > .btnText")',
                        "PRP_STG_CREATEOpty_CREATEQuote_Pricing"
                      ),
                      $browser
                        .waitForAndFindElement(
                          By.css("#refreshbtn > .btnText"),
                          DefaultTimeout
                        )
                        .then((e) => (e.click(), Promise.resolve(!0)))
                    );
                  })
                  .then(function () {
                    return (
                      logger.log(
                        30,
                        'Click By.css("#validatebtn > .btnText")',
                        "PRP_STG_CREATEOpty_CREATEQuote_Pricing"
                      ),
                      $browser
                        .waitForAndFindElement(
                          By.css("#validatebtn > .btnText"),
                          DefaultTimeout
                        )
                        .then((e) => (e.click(), Promise.resolve(!0)))
                    );
                  })
                  .then(function () {
                    return (
                      logger.log(
                        31,
                        "Close Browser",
                        "PRP_STG_CREATEOpty_CREATEQuote_Pricing"
                      ),
                      Promise.resolve($browser.close())
                    );
                  })
              
              }) //------
        });
});

$browser.getAllWindowHandles().then(function(windowHandlers) {
    $browser.switchTo().window(windowHandlers[0]).then(function() {
        $browser.getCapabilities().then(function () {
            $browser.manage().timeouts().setScriptTimeout(ScriptTimeout);
            $browser.manage().timeouts().pageLoadTimeout(DefaultTimeout);
            $browser.manage().timeouts().implicitlyWait(WaitTimeout);})
            .then(() => {
                Promise.resolve(true)
                .then(function () {
                    return (
                      logger.log(
                        32,
                        'Switch to Window using Handle vars.get("root")',
                        "PRP_STG_CREATEOpty_CREATEQuote_Pricing"
                      ),
                      Promise.resolve($browser.switchTo().window(vars.get("root")))
                    );
                  })
                  .then(function () {
                    return (
                      logger.log(
                        33,
                        'Click By.css("#userIconImg > img")',
                        "PRP_STG_CREATEOpty_CREATEQuote_Pricing"
                      ),
                      $browser
                        .waitForAndFindElement(By.css("#userIconImg > img"), DefaultTimeout)
                        .then((e) => (e.click(), Promise.resolve(!0)))
                    );
                  })
                  .then(function () {
                    return (
                      logger.log(
                        34,
                        'Click By.linkText("Sign out")',
                        "PRP_STG_CREATEOpty_CREATEQuote_Pricing"
                      ),
                      $browser
                        .waitForAndFindElement(By.linkText("Sign out"), DefaultTimeout)
                        .then((e) => (e.click(), Promise.resolve(!0)))
                    );
                  })
                  .then(function () {
                    return (
                      logger.log(
                        35,
                        "Close Browser",
                        "PRP_STG_CREATEOpty_CREATEQuote_Pricing"
                      ),
                      Promise.resolve($browser.close())
                    );
                  })
                  .then(
                    function () {
                      logger.endTestCase("PRP_STG_CREATEOpty_CREATEQuote_Pricing");
                    },
                    function (err) {
                      logger.error(err, "PRP_STG_CREATEOpty_CREATEQuote_Pricing");
                      throw err;
                    }
                  )
            })
})
});